import Foundation

enum CleanupCategory: String, CaseIterable, Hashable, Sendable {
    case derivedData          = "DerivedData"
    case simulators           = "Simulators"
    case runtimes             = "Runtimes"
    case metroCache           = "Metro Cache"
    case gradleCache          = "Gradle Cache"
    case cocoapods            = "CocoaPods Cache"
    case archives             = "Xcode Archives"
    case watchman             = "Watchman Cache"
    case androidBuildOutputs  = "Android Build Outputs"
    case iosDeviceSupport     = "iOS Device Support"
    case appLogs              = "Application Logs"
    case crashReports         = "Crash Reports"

    var systemImage: String {
        switch self {
        case .derivedData:         return "hammer"
        case .simulators:          return "iphone"
        case .runtimes:            return "square.stack.3d.down.right"
        case .metroCache:          return "bolt"
        case .gradleCache:         return "square.stack.3d.down.right.fill"
        case .cocoapods:           return "shippingbox"
        case .archives:            return "archivebox"
        case .watchman:            return "eye.slash"
        case .androidBuildOutputs: return "wrench.and.screwdriver"
        case .iosDeviceSupport:    return "iphone.and.arrow.forward"
        case .appLogs:             return "doc.text"
        case .crashReports:        return "exclamationmark.triangle"
        }
    }

    var riskLevel: CleanupRiskLevel {
        switch self {
        case .derivedData:         return .safe
        case .simulators:          return .moderate
        case .runtimes:            return .caution
        case .metroCache:          return .safe
        case .gradleCache:         return .safe
        case .cocoapods:           return .safe
        case .archives:            return .caution
        case .watchman:            return .safe
        case .androidBuildOutputs: return .safe
        case .iosDeviceSupport:    return .moderate
        case .appLogs:             return .safe
        case .crashReports:        return .safe
        }
    }

    var hint: String {
        switch self {
        case .derivedData:
            return "Rebuilt automatically on next build. Safe to delete any time."
        case .simulators:
            return "Removes simulator device data. Reinstalling apps will be required."
        case .runtimes:
            return "Removes downloaded OS images. Re-downloading from Xcode will be required."
        case .metroCache:
            return "Rebuilt on next `npx react-native start`. No data lost."
        case .gradleCache:
            return "Dependencies are re-downloaded from Maven/Gradle on the next Android build."
        case .cocoapods:
            return "Re-downloaded on the next `pod install` run."
        case .archives:
            return "Exported .xcarchive bundles. These cannot be recovered once deleted."
        case .watchman:
            return "Watchman file-watch state. Automatically rebuilt when Watchman restarts."
        case .androidBuildOutputs:
            return "APKs, AABs, native .so libraries, and compiled classes inside project build/ folders. Fully regenerated on the next Android/React Native build."
        case .iosDeviceSupport:
            return "Debug symbol packages (~2–4 GB each) downloaded when you connected a physical device. Older iOS versions you no longer debug can be safely removed. Xcode re-downloads them if needed."
        case .appLogs:
            return "Log files generated by macOS apps and developer tools. Automatically recreated when apps run."
        case .crashReports:
            return "Crash and hang diagnostic reports. Safe to delete — they accumulate over time and are rarely needed after issues are resolved."
        }
    }

    // Root folder URL for this category — used for "Open in Finder".
    // Returns nil for categories without a single canonical root (e.g. Android build outputs).
    var rootURL: URL? {
        let home = NSHomeDirectory()
        switch self {
        case .derivedData:         return URL(fileURLWithPath: "\(home)/Library/Developer/Xcode/DerivedData")
        case .simulators:          return URL(fileURLWithPath: "\(home)/Library/Developer/CoreSimulator/Devices")
        case .runtimes:            return URL(fileURLWithPath: "\(home)/Library/Developer/CoreSimulator/Runtimes")
        case .archives:            return URL(fileURLWithPath: "\(home)/Library/Developer/Xcode/Archives")
        case .metroCache:          return URL(fileURLWithPath: "\(home)/Library/Caches/Metro")
        case .gradleCache:         return URL(fileURLWithPath: "\(home)/.gradle/caches")
        case .cocoapods:           return URL(fileURLWithPath: "\(home)/Library/Caches/CocoaPods")
        case .watchman:            return URL(fileURLWithPath: "\(home)/Library/Caches/com.github.facebook.watchman")
        case .iosDeviceSupport:    return URL(fileURLWithPath: "\(home)/Library/Developer/Xcode/iOS DeviceSupport")
        case .appLogs:             return URL(fileURLWithPath: "\(home)/Library/Logs")
        case .crashReports:        return URL(fileURLWithPath: "\(home)/Library/Logs/DiagnosticReports")
        case .androidBuildOutputs: return nil
        }
    }
}
